name: example
description: A project used to demo the GetxDependenciesBindingAnnotation
version: 1.0.0+2

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  getx_dependencies_binding_annotation:
    path: ../annotation/

dev_dependencies:
  build_runner: ^2.4.9
  getx_dependencies_binding_annotation_generator:
    path: ../generator/