name: getx_dependencies_binding_annotation
description: Getx Dependencies Binding Annotation
author: Resam Taghipour <resam.t@gmail.com>
version: 0.0.1
repository: https://github.com/reesaam/flutter_getx_dependencies_binding_annotation

environment:
  sdk: '>=3.4.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  get: ^4.6.6
  build: ^2.4.1
  build_runner: ^2.4.10
  code_builder: ^4.10.0
  dart_style: ^2.3.7
  json_annotation: ^4.9.0
  # path: ^1.8.0

  getx_dependencies_binding_annotation:
    path: /lib/src/base.dart


dev_dependencies:
  build_config: ^1.1.1
  build_verify: ^3.1.0
  build_test: ^2.2.2
  source_gen: ^1.5.0
  lint: ^2.3.0
  lints: ^4.0.0
  flutter_lints: ^4.0.0
  test: ^1.24.0

flutter:
  generate: true