name: getx_binding_annotation
description: A Code Generator Plugin to Generate Pages and Dependencies for GetX State Manager base on Annotation.
version: 0.1.1
homepage: https://www.resam.site
repository: https://github.com/reesaam/flutter_getx_dependencies_binding_annotation.git
funding:
  - https://resam.site

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.5.3

dependencies:
  build_runner: ^2.4.13
  dartdoc: ^8.0.8

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  getx_binding_annotation_generator:
    path: ../generator/