name: getx_dependencies_binding_annotation
description: Getx Dependencies Binding Annotation
version: 0.0.2
homepage: https://www.linkedin.com/in/resam
repository: https://github.com/reesaam/flutter_getx_dependencies_binding_annotation

environment:
  sdk: ^3.5.3

dependencies:
  build_runner: ^2.4.13
  dartdoc: ^8.0.8
  getx_dependencies_binding_annotation_generator:
    path: ../generator/

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0